import PySide6.QtCore as QtCore

QtKeyBoardStringDict = {
    QtCore.Qt.Key_A: {"Hex": 0x41, "String": "a"},
    QtCore.Qt.Key_B: {"Hex": 0x42, "String": "b"},
    QtCore.Qt.Key_C: {"Hex": 0x43, "String": "c"},
    QtCore.Qt.Key_D: {"Hex": 0x44, "String": "d"},
    QtCore.Qt.Key_E: {"Hex": 0x45, "String": "e"},
    QtCore.Qt.Key_F: {"Hex": 0x46, "String": "f"},
    QtCore.Qt.Key_G: {"Hex": 0x47, "String": "g"},
    QtCore.Qt.Key_H: {"Hex": 0x48, "String": "h"},
    QtCore.Qt.Key_I: {"Hex": 0x49, "String": "i"},
    QtCore.Qt.Key_J: {"Hex": 0x4a, "String": "j"},
    QtCore.Qt.Key_K: {"Hex": 0x4b, "String": "k"},
    QtCore.Qt.Key_L: {"Hex": 0x4c, "String": "l"},
    QtCore.Qt.Key_M: {"Hex": 0x4d, "String": "m"},
    QtCore.Qt.Key_N: {"Hex": 0x4e, "String": "n"},
    QtCore.Qt.Key_O: {"Hex": 0x4f, "String": "o"},
    QtCore.Qt.Key_P: {"Hex": 0x50, "String": "p"},
    QtCore.Qt.Key_Q: {"Hex": 0x51, "String": "q"},
    QtCore.Qt.Key_R: {"Hex": 0x52, "String": "r"},
    QtCore.Qt.Key_S: {"Hex": 0x53, "String": "s"},
    QtCore.Qt.Key_T: {"Hex": 0x54, "String": "t"},
    QtCore.Qt.Key_U: {"Hex": 0x55, "String": "u"},
    QtCore.Qt.Key_V: {"Hex": 0x56, "String": "v"},
    QtCore.Qt.Key_W: {"Hex": 0x57, "String": "w"},
    QtCore.Qt.Key_X: {"Hex": 0x58, "String": "x"},
    QtCore.Qt.Key_Y: {"Hex": 0x59, "String": "y"},
    QtCore.Qt.Key_Z: {"Hex": 0x5a, "String": "z"}, 
    QtCore.Qt.Key_1: {"Hex": 0x31, "String": "1"},
    QtCore.Qt.Key_2: {"Hex": 0x32, "String": "2"},
    QtCore.Qt.Key_3: {"Hex": 0x33, "String": "3"},
    QtCore.Qt.Key_4: {"Hex": 0x34, "String": "4"},
    QtCore.Qt.Key_5: {"Hex": 0x35, "String": "5"},
    QtCore.Qt.Key_6: {"Hex": 0x36, "String": "6"},
    QtCore.Qt.Key_7: {"Hex": 0x37, "String": "7"},
    QtCore.Qt.Key_8: {"Hex": 0x38, "String": "8"},
    QtCore.Qt.Key_9: {"Hex": 0x39, "String": "9"},
    QtCore.Qt.Key_0: {"Hex": 0x30, "String": "0"}, 
    QtCore.Qt.Key_Up: {"Hex": 0x1012, "String": "Up"}, 
    QtCore.Qt.Key_Down: {"Hex": 0x1013, "String": "Down"}, 
    QtCore.Qt.Key_Left: {"Hex": 0x1014, "String": "Left"}, 
    QtCore.Qt.Key_Right: {"Hex": 0x1015, "String": "Right"}, 
}