import PySide6.QtCore as QtCore

QtKeyBoardStringDict = {
    QtCore.Qt.Key_A: {"Hex": 0x41, "String": "a", "VirtualKey": 0x41},
    QtCore.Qt.Key_B: {"Hex": 0x42, "String": "b", "VirtualKey": 0x42},
    QtCore.Qt.Key_C: {"Hex": 0x43, "String": "c", "VirtualKey": 0x43},
    QtCore.Qt.Key_D: {"Hex": 0x44, "String": "d", "VirtualKey": 0x44},
    QtCore.Qt.Key_E: {"Hex": 0x45, "String": "e", "VirtualKey": 0x45},
    QtCore.Qt.Key_F: {"Hex": 0x46, "String": "f", "VirtualKey": 0x46},
    QtCore.Qt.Key_G: {"Hex": 0x47, "String": "g", "VirtualKey": 0x47},
    QtCore.Qt.Key_H: {"Hex": 0x48, "String": "h", "VirtualKey": 0x48},
    QtCore.Qt.Key_I: {"Hex": 0x49, "String": "i", "VirtualKey": 0x49},
    QtCore.Qt.Key_J: {"Hex": 0x4a, "String": "j", "VirtualKey": 0x4A},
    QtCore.Qt.Key_K: {"Hex": 0x4b, "String": "k", "VirtualKey": 0x4B},
    QtCore.Qt.Key_L: {"Hex": 0x4c, "String": "l", "VirtualKey": 0x4C},
    QtCore.Qt.Key_M: {"Hex": 0x4d, "String": "m", "VirtualKey": 0x4D},
    QtCore.Qt.Key_N: {"Hex": 0x4e, "String": "n", "VirtualKey": 0x4E},
    QtCore.Qt.Key_O: {"Hex": 0x4f, "String": "o", "VirtualKey": 0x4F},
    QtCore.Qt.Key_P: {"Hex": 0x50, "String": "p", "VirtualKey": 0x50},
    QtCore.Qt.Key_Q: {"Hex": 0x51, "String": "q", "VirtualKey": 0x51},
    QtCore.Qt.Key_R: {"Hex": 0x52, "String": "r", "VirtualKey": 0x52},
    QtCore.Qt.Key_S: {"Hex": 0x53, "String": "s", "VirtualKey": 0x53},
    QtCore.Qt.Key_T: {"Hex": 0x54, "String": "t", "VirtualKey": 0x54},
    QtCore.Qt.Key_U: {"Hex": 0x55, "String": "u", "VirtualKey": 0x55},
    QtCore.Qt.Key_V: {"Hex": 0x56, "String": "v", "VirtualKey": 0x56},
    QtCore.Qt.Key_W: {"Hex": 0x57, "String": "w", "VirtualKey": 0x57},
    QtCore.Qt.Key_X: {"Hex": 0x58, "String": "x", "VirtualKey": 0x58},
    QtCore.Qt.Key_Y: {"Hex": 0x59, "String": "y", "VirtualKey": 0x59},
    QtCore.Qt.Key_Z: {"Hex": 0x5a, "String": "z", "VirtualKey": 0x5A},
    QtCore.Qt.Key_1: {"Hex": 0x31, "String": "1", "VirtualKey": 0x31},
    QtCore.Qt.Key_2: {"Hex": 0x32, "String": "2", "VirtualKey": 0x32},
    QtCore.Qt.Key_3: {"Hex": 0x33, "String": "3", "VirtualKey": 0x33},
    QtCore.Qt.Key_4: {"Hex": 0x34, "String": "4", "VirtualKey": 0x34},
    QtCore.Qt.Key_5: {"Hex": 0x35, "String": "5", "VirtualKey": 0x35},
    QtCore.Qt.Key_6: {"Hex": 0x36, "String": "6", "VirtualKey": 0x36},
    QtCore.Qt.Key_7: {"Hex": 0x37, "String": "7", "VirtualKey": 0x37},
    QtCore.Qt.Key_8: {"Hex": 0x38, "String": "8", "VirtualKey": 0x38},
    QtCore.Qt.Key_9: {"Hex": 0x39, "String": "9", "VirtualKey": 0x39},
    QtCore.Qt.Key_0: {"Hex": 0x30, "String": "0", "VirtualKey": 0x30},
    QtCore.Qt.Key_Up: {"Hex": 0x1012, "String": "Up", "VirtualKey": 0x26},
    QtCore.Qt.Key_Down: {"Hex": 0x1013, "String": "Down", "VirtualKey": 0x28},
    QtCore.Qt.Key_Left: {"Hex": 0x1014, "String": "Left", "VirtualKey": 0x25},
    QtCore.Qt.Key_Right: {"Hex": 0x1015, "String": "Right", "VirtualKey": 0x27},
}